apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: karsajobs
        tier: frontend
    spec:
      containers:
      - name: karsajobs-ui
        image: aminullohzaqi/karsajobs-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
        env:
          - name: VUE_APP_BACKEND
            value: http://127.0.0.1:36253