version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq_container'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_network
  order:
    image: aminullohzaqi/order-service:latest
    container_name: 'order-service_container'
    ports:
      - 3000:3000
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
  shipping:
    image: aminullohzaqi/shipping-service:latest
    container_name: 'shipping-service_container'
    ports:
      - 3001:3001
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge