# versi docker compose
version: "3.7"

# membuat services
services:
  # service item-app
  item-app:
    # ambil images dari docker hub
    image: aminullohzaqi/item-app:v1
    # selalu restart jika terhenti
    restart: always
    # memberi akses untuk port 80 di host agar terhubung dengan 8080 di container
    ports:
      - 80:8080
    # memastikan container berjalan setelah item-db running
    depends_on: 
      - item-db
  # service item-db
  item-db:
    # ambil image dari docker hub
    image: mongo:3
    # menghubungkan volume
    volumes:
      - app-db:/data/db

# membuat volume dengan nama app-db
volumes:
  app-db: